condense_wildcard_suffixes = true
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
max_width = 120
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
